### ISSUE TITLE
Invalid link on CodeFusion Studio Welcome page to download CodeFusion SDK

### ISSUE THREAD

**Issue by DaveB-ADI** [analogdevicesinc/codefusion-studio#1]
## Description
Invalid link on CodeFusion Studio Welcome page to download CodeFusion SDK

Link on Welcome page points to : https://www.analog.com/en/codefusionstudio.html
When it should be : https://www.analog.com/en/resources/evaluation-hardware-and-software/embedded-development-software/codefusion-studio.html#software-requirement

## Your Environment
- VS Code CFS extension version : v1.0.0
- VS Code version:1.94.0
- Operating System and version : Windows

**Comment by mharringADI** [comment]
Thanks @DaveB-ADI - the original URL should be live now.
